export type UiLang = 'en' | 'cy'

export const uiStrings = {
  en: {
    // Sidebar
    content: 'Content',
    addNew: 'ADD NEW',
    books: 'Books',
    biographies: 'Biographies',
    stories: 'Stories',
    paintings: 'Paintings',
    artefacts: 'Artefacts',
    locations: 'Locations',
    adminUsers: 'Admin Users',
    logOut: 'LOG OUT',
    noBooksAvailable: 'No books available.',
    noBiographiesAvailable: 'No biographies available.',
    noStoriesAvailable: 'No stories available.',
    noPaintingsAvailable: 'No paintings available.',
    noArtefactsAvailable: 'No artefacts available.',
    // Editor header
    menu: 'Menu',
    newContent: 'New Content',
    editContent: 'Edit Content',
    // Form sections
    selectContentType: 'Select Content Type',
    selectStoryType: 'Select Story Type',
    selectMedium: 'Select Medium',
    selectCategory: 'Select Category',
    addStoryType: '+ Add story type',
    addMedium: '+ Add medium',
    addCategory: '+ Add category',
    // Content type selector labels
    contentTypeBook: 'Book',
    contentTypeStories: 'Stories',
    contentTypePainting: 'Painting',
    contentTypeArtefacts: 'Artefacts',
    contentTypeBio: 'Bio',
    // SEO
    seo: 'SEO',
    seoHint: 'Hidden by default. SEO title and description are auto-filled unless you edit them.',
    // Publishing settings
    publishingSettings: 'Publishing Settings',
    publishingHint: 'Hidden by default. Slug is auto-generated, sort order defaults to 100, featured image is blank unless set.',
    featured: 'Featured',
    published: 'Published',
    // Action buttons
    archive: 'ARCHIVE',
    save: 'SAVE',
    saving: 'SAVING...',
    updating: 'UPDATING...',
    preview: 'PREVIEW',
    publish: 'PUBLISH',
    // Modal shared
    close: 'CLOSE',
    cancel: 'CANCEL',
    confirm: 'CONFIRM',
    creating: 'CREATING...',
    // Preview modal
    previewTitle: 'Preview',
    previewBody: 'Preview functionality is coming soon.',
    // Publish modal
    publishTitle: 'Publish content',
    publishBody: 'This will make the content publicly visible on the site. Are you sure you want to publish?',
    confirmPublish: 'CONFIRM PUBLISH',
    contentPublished: 'Content published.',
    // Unpublish modal
    unpublish: 'UNPUBLISH',
    unpublishTitle: 'Unpublish content',
    unpublishBody: 'This will hide the content from the public site. Are you sure you want to unpublish?',
    confirmUnpublish: 'CONFIRM UNPUBLISH',
    contentUnpublished: 'Content unpublished.',
    // Archive modal
    archiveTitle: 'Archive content',
    archiveBody: 'Are you sure you want to archive this content item? It will be hidden from the public but can be restored later.',
    confirmArchive: 'CONFIRM ARCHIVE',
    // Genre modal
    newGenreTitle: 'New Genre',
    genrePlaceholder: 'Genre name',
    genrePlaceholderEn: 'Genre name (English)',
    genrePlaceholderCy: 'Genre name (Welsh)',
    // Story type modal
    newStoryTypeTitle: 'New Story Type',
    storyTypePlaceholder: 'Story type name',
    storyTypePlaceholderEn: 'Story type name (English)',
    storyTypePlaceholderCy: 'Story type name (Welsh)',
    // Medium modal
    newMediumTitle: 'New Medium',
    mediumPlaceholder: 'Medium name',
    mediumPlaceholderEn: 'Medium name (English)',
    mediumPlaceholderCy: 'Medium name (Welsh)',
    // Category modal
    newCategoryTitle: 'New Artefact Category',
    categoryPlaceholder: 'Category name',
    categoryPlaceholderEn: 'Category name (English)',
    categoryPlaceholderCy: 'Category name (Welsh)',
    // Toasts
    contentUpdated: 'Content updated.',
    contentSaved: 'Content saved.',
    // Shared form
    welshSuffix: 'Welsh',
    englishSuffix: 'English',
    // ImageManager
    imagery: 'Imagery',
    primary: 'Primary',
    additionalImagery: 'Additional Imagery',
    uploading: 'Uploading...',
    setAsPrimaryImage: 'Set as primary image',
    altText: 'Alt text',
    caption: 'Caption',
    credit: 'Credit',
    location: 'Location',
    selectFromLocations: 'Select from Locations',
    setLocation: 'SET LOCATION',
    pinSelected: 'Pin selected',
    qrCode: 'QR Code',
    enterSlugQr: 'Enter slug / QR value',
    generateQrCode: 'GENERATE QR CODE',
    checkingSlug: 'Checking slug availability…',
    slugTaken: 'This slug is already in use. Please choose a different one.',
    printQrCode: 'PRINT QR CODE',
    uploadActivity: 'Upload activity',
    preparingUpload: 'Preparing upload...',
    selectLocationTitle: 'Select Location',
    clickMapPin: 'Click anywhere on the map to drop a pin.',
    coordinatesSelected: 'Selected',
    noPinSelected: 'No pin selected yet.',
    updateLocation: 'UPDATE LOCATION',
    addLocation: 'ADD LOCATION',
    pleaseEnterSlug: 'Please enter a slug before generating a QR code.',
    qrCodeGenerated: 'QR code generated.',
    locationConfirmed: 'Location confirmed and saved.',
    pleaseDropPin: 'Please drop a pin before confirming location.',
    locationSelectedSaveFirst: 'Location selected. Save the content item first to persist it.',
    locationSaved: 'Location saved.',
    imageUploadedSuccessfully: 'Image uploaded successfully.',
    deleteImageTitle: 'Delete image',
    deleteImageBody: 'Are you sure you want to delete this image? This cannot be undone.',
    confirmDelete: 'CONFIRM DELETE',
    // AudioGuide
    audioGuide: 'Audio Guide',
    audioGuideEnglish: 'English Audio Guide',
    audioGuideWelsh: 'Welsh Audio Guide',
    uploadingAudio: 'UPLOADING...',
    uploadAudioGuide: 'UPLOAD AUDIO GUIDE',
    audioFileRequirements: 'File requirements – Format .mp3 or .mp4, Max size 15mb',
    audioMp3Only: 'Only MP3 or MP4 audio files are allowed.',
    audioFileTooLarge: 'File exceeds 15MB limit.',
    saveBeforeAudio: 'Save the content item before uploading an audio guide.',
    // ConnectedContent
    connectedContent: 'Connected Content',
    connectedSearchHint: 'Search existing content to connect this',
    connectedSearchWith: 'with.',
    searchContent: 'Search content...',
    searching: 'Searching…',
    saveBeforeConnecting: 'Save the content item before adding connections.',
    allTab: 'All',
    connectedTypeBook: 'book',
    connectedTypeStory: 'story',
    connectedTypePainting: 'painting',
    connectedTypeArtefact: 'artefact',
    connectedTypeBiography: 'biography',
    connectedTypeItem: 'item',
    sortOrder: 'Sort Order',
    title: 'Title',
    description: 'Description',
    summary: 'Summary',
    dimensions: 'Dimensions',
    // Book form
    bookGenres: 'Book Genres',
    bookDetails: 'Book Details',
    selectOrAddGenre: 'Select or add a genre',
    addGenre: 'ADD GENRE',
    bookTitle: 'Book Title',
    author: 'Author',
    publisher: 'Publisher',
    isbn: 'ISBN',
    publicationDate: 'Publication Date',
    pagesCount: 'Pages Count',
    detailedContent: 'Detailed Content',
    // Story form
    storyDetails: 'Story Details',
    storyTitle: 'Story Title',
    subtitleSummary: 'Subtitle / Summary',
    storyContent: 'Story Content',
    // Painting form
    paintingDetails: 'Painting Details',
    artist: 'Artist/s',
    artistHint: 'Kate Waters, Sarah Roberts',
    yearCreatedLabel: 'Date',
    yearCreatedPlaceholder: 'YYYY',
    itemId: 'Item ID#',
    dimensionH: 'H',
    dimensionW: 'W',
    dimensionD: 'D',
    cmUnit: 'cm',
    // Artefact form
    artefactDetails: 'Artefact Details',
    datePeriod: 'Date Period',
    material: 'Material',
    maker: 'Artist/s',
    makerHint: 'Kate Waters, Sarah Roberts',
    dateTimePeriod: 'Date / Time Period',
    dateStart: 'Start',
    dateEnd: 'End',
    dateDay: 'Day',
    dateMonth: 'MM',
    dateYear: 'YEAR',
    dateAD: 'AD',
    dateBC: 'BC',
    orHistoricalPeriodOrEra: 'Or select a historical period or era instead of a date range',
    periodLabel: 'Period',
    eraLabel: 'Era',
    selectHistoricalPeriod: 'Select historical period if applicable',
    selectHistoricalEra: 'Select historical era if applicable',
    addPeriod: '+ Add period',
    addEra: '+ Add era',
    newPeriodTitle: 'New Historical Period',
    newEraTitle: 'New Historical Era',
    periodNamePlaceholder: 'Period name',
    eraNamePlaceholder: 'Era name',
    // Bio form
    biographyDetails: 'Biography Details',
    fullName: 'Full Name',
    occupation: 'Occupation',
    birthLabel: 'Birth',
    deathLabel: 'Death',
    birthYear: 'Birth Year',
    deathYear: 'Death Year',
    shortSummary: 'Short summary',
    fullBiographyContent: 'Full biography content',
  },
  cy: {
    // Sidebar
    content: 'Cynnwys',
    addNew: 'YCHWANEGU NEWYDD',
    books: 'Llyfrau',
    biographies: 'Bywgraffiadau',
    stories: 'Straeon',
    paintings: 'Peintiadau',
    artefacts: 'Arteffactau',
    locations: 'Lleoliadau',
    adminUsers: 'Defnyddwyr Gweinyddol',
    logOut: 'ALLGOFNODI',
    noBooksAvailable: 'Dim llyfrau ar gael.',
    noBiographiesAvailable: 'Dim bywgraffiadau ar gael.',
    noStoriesAvailable: 'Dim straeon ar gael.',
    noPaintingsAvailable: 'Dim peintiadau ar gael.',
    noArtefactsAvailable: 'Dim arteffactau ar gael.',
    // Editor header
    menu: 'Dewislen',
    newContent: 'Cynnwys Newydd',
    editContent: 'Golygu Cynnwys',
    // Form sections
    selectContentType: 'Dewiswch Fath o Gynnwys',
    selectStoryType: 'Dewiswch Fath o Stori',
    selectMedium: 'Dewiswch Gyfrwng',
    selectCategory: 'Dewiswch Gategori',
    addStoryType: '+ Ychwanegu math o stori',
    addMedium: '+ Ychwanegu cyfrwng',
    addCategory: '+ Ychwanegu categori',
    // Content type selector labels
    contentTypeBook: 'Llyfr',
    contentTypeStories: 'Straeon',
    contentTypePainting: 'Peintiad',
    contentTypeArtefacts: 'Arteffactau',
    contentTypeBio: 'Byw',
    // SEO
    seo: 'SEO',
    seoHint: "Cudd yn ddiofyn. Llenwir y teitl a'r disgrifiad SEO yn awtomatig oni bai eich bod yn eu golygu.",
    // Publishing settings
    publishingSettings: 'Gosodiadau Cyhoeddi',
    publishingHint: "Cudd yn ddiofyn. Cynhyrchir y slug yn awtomatig, mae'r drefn ddidoli yn 100 yn ddiofyn, mae'r ddelwedd brif yn wag oni osodir.",
    featured: 'Amlwg',
    published: 'Cyhoeddwyd',
    // Action buttons
    archive: 'ARCHIFIO',
    save: 'CADW',
    saving: 'YN CADW...',
    updating: 'YN DIWEDDARU...',
    preview: 'RHAGOLWG',
    publish: 'CYHOEDDI',
    // Modal shared
    close: 'CAU',
    cancel: 'CANSLO',
    confirm: 'CADARNHAU',
    creating: 'YN CREU...',
    // Preview modal
    previewTitle: 'Rhagolwg',
    previewBody: 'Daw ymarferoldeb rhagolwg yn fuan.',
    // Publish modal
    publishTitle: 'Cyhoeddi cynnwys',
    publishBody: 'Bydd hyn yn gwneud y cynnwys yn weladwy i\'r cyhoedd ar y safle. Ydych chi\'n sicr am gyhoeddi?',
    confirmPublish: 'CADARNHAU CYHOEDDI',
    contentPublished: 'Cynnwys wedi\'i gyhoeddi.',
    // Unpublish modal
    unpublish: 'DADFYHOEDDI',
    unpublishTitle: 'Dadfyhoeddi cynnwys',
    unpublishBody: 'Bydd hyn yn cuddio\'r cynnwys o\'r safle cyhoeddus. Ydych chi\'n sicr am dadfyhoeddi?',
    confirmUnpublish: 'CADARNHAU DADFYHOEDDI',
    contentUnpublished: 'Cynnwys wedi\'i dadfyhoeddi.',
    // Archive modal
    archiveTitle: 'Archifio cynnwys',
    archiveBody: "Ydych chi'n sicr am archifio'r eitem cynnwys hon? Bydd yn gudd i'r cyhoedd ond gellir ei hadfer yn ddiweddarach.",
    confirmArchive: 'CADARNHAU ARCHIF',
    // Genre modal
    newGenreTitle: 'Genre Newydd',
    genrePlaceholder: 'Enw genre',
    genrePlaceholderEn: 'Enw genre (Saesneg)',
    genrePlaceholderCy: 'Enw genre (Cymraeg)',
    // Story type modal
    newStoryTypeTitle: 'Math Newydd o Stori',
    storyTypePlaceholder: 'Enw math o stori',
    storyTypePlaceholderEn: 'Enw math o stori (Saesneg)',
    storyTypePlaceholderCy: 'Enw math o stori (Cymraeg)',
    // Medium modal
    newMediumTitle: 'Cyfrwng Newydd',
    mediumPlaceholder: 'Enw cyfrwng',
    mediumPlaceholderEn: 'Enw cyfrwng (Saesneg)',
    mediumPlaceholderCy: 'Enw cyfrwng (Cymraeg)',
    // Category modal
    newCategoryTitle: 'Categori Arteffact Newydd',
    categoryPlaceholder: 'Enw categori',
    categoryPlaceholderEn: 'Enw categori (Saesneg)',
    categoryPlaceholderCy: 'Enw categori (Cymraeg)',
    // Toasts
    contentUpdated: "Cynnwys wedi'i ddiweddaru.",
    contentSaved: "Cynnwys wedi'i gadw.",
    // Shared form
    welshSuffix: 'Cymraeg',
    englishSuffix: 'Saesneg',
    // ImageManager
    imagery: 'Delweddaeth',
    primary: 'Prif',
    additionalImagery: 'Delweddaeth Ychwanegol',
    uploading: 'Yn uwchlwytho...',
    setAsPrimaryImage: 'Gosod fel prif ddelwedd',
    altText: 'Testun amgen',
    caption: 'Pennawd',
    credit: 'Credyd',
    location: 'Lleoliad',
    selectFromLocations: 'Dewiswch o Lleoliadau',
    setLocation: 'GOSOD LLEOLIAD',
    pinSelected: 'Pin wedi\'i ddewis',
    qrCode: 'Cod QR',
    enterSlugQr: 'Rhowch slug / gwerth QR',
    generateQrCode: 'CYNHYRCHU COD QR',
    checkingSlug: 'Yn gwirio argaeledd slug…',
    slugTaken: 'Mae\'r slug hwn eisoes mewn defnydd. Dewiswch un gwahanol.',
    printQrCode: 'ARGRAFFU COD QR',
    uploadActivity: 'Gweithgaredd uwchlwytho',
    preparingUpload: 'Yn paratoi uwchlwythiad...',
    selectLocationTitle: 'Dewis Lleoliad',
    clickMapPin: 'Cliciwch unrhyw le ar y map i osod pin.',
    coordinatesSelected: 'Dewisiad',
    noPinSelected: 'Dim pin wedi\'i ddewis eto.',
    updateLocation: 'DIWEDDARU LLEOLIAD',
    addLocation: 'YCHWANEGU LLEOLIAD',
    pleaseEnterSlug: 'Rhowch slug cyn cynhyrchu cod QR.',
    qrCodeGenerated: 'Cod QR wedi\'i gynhyrchu.',
    locationConfirmed: 'Lleoliad wedi\'i gadarnhau a\'i gadw.',
    pleaseDropPin: 'Gosodwch bin cyn cadarnhau\'r lleoliad.',
    locationSelectedSaveFirst: 'Lleoliad wedi\'i ddewis. Cadwch yr eitem cynnwys yn gyntaf i\'w gadw.',
    locationSaved: 'Lleoliad wedi\'i gadw.',
    imageUploadedSuccessfully: 'Delwedd wedi\'i huwchlwytho\'n llwyddiannus.',
    deleteImageTitle: 'Dileu delwedd',
    deleteImageBody: 'Ydych chi\'n sicr eich bod am ddileu\'r ddelwedd hon? Ni ellir dadwneud hyn.',
    confirmDelete: 'CADARNHAU DILEU',
    // AudioGuide
    audioGuide: 'Canllaw Sain',
    audioGuideEnglish: 'Canllaw Sain Saesneg',
    audioGuideWelsh: 'Canllaw Sain Cymraeg',
    uploadingAudio: 'YN UWCHLWYTHO...',
    uploadAudioGuide: 'UWCHLWYTHO CANLLAW SAIN',
    audioFileRequirements: 'Gofynion ffeil – Fformat .mp3 neu .mp4, Maint uchaf 15mb',
    audioMp3Only: 'Dim ond ffeiliau sain MP3 neu MP4 a ganiateir.',
    audioFileTooLarge: 'Mae\'r ffeil yn fwy na\'r terfyn 15MB.',
    saveBeforeAudio: 'Cadwch yr eitem cynnwys cyn uwchlwytho canllaw sain.',
    // ConnectedContent
    connectedContent: 'Cynnwys Cysylltiedig',
    connectedSearchHint: 'Chwiliwch am gynnwys presennol i gysylltu\'r',
    connectedSearchWith: 'hwn ag ef.',
    searchContent: 'Chwilio cynnwys...',
    searching: 'Yn chwilio…',
    saveBeforeConnecting: 'Cadwch yr eitem cynnwys cyn ychwanegu cysylltiadau.',
    allTab: 'Pob Un',
    connectedTypeBook: 'llyfr',
    connectedTypeStory: 'stori',
    connectedTypePainting: 'peintiad',
    connectedTypeArtefact: 'arteffact',
    connectedTypeBiography: 'bywgraffiad',
    connectedTypeItem: 'eitem',
    sortOrder: 'Trefn Didoli',
    title: 'Teitl',
    description: 'Disgrifiad',
    summary: 'Crynodeb',
    dimensions: 'Dimensiynau',
    // Book form
    bookGenres: 'Genres Llyfr',
    bookDetails: 'Manylion Llyfr',
    selectOrAddGenre: 'Dewiswch neu ychwanegwch genre',
    addGenre: 'YCHWANEGU GENRE',
    bookTitle: 'Teitl y Llyfr',
    author: 'Awdur',
    publisher: 'Cyhoeddwr',
    isbn: 'ISBN',
    publicationDate: 'Dyddiad Cyhoeddi',
    pagesCount: 'Nifer y Tudalennau',
    detailedContent: 'Cynnwys Manwl',
    // Story form
    storyDetails: 'Manylion Stori',
    storyTitle: 'Teitl y Stori',
    subtitleSummary: 'Is-deitl / Crynodeb',
    storyContent: "Cynnwys y Stori",
    // Painting form
    paintingDetails: 'Manylion Peintiad',
    artist: 'Arlunydd/wyr',
    artistHint: 'Kate Waters, Sarah Roberts',
    yearCreatedLabel: 'Dyddiad',
    yearCreatedPlaceholder: 'BBBB',
    itemId: 'ID Eitem#',
    dimensionH: 'U',
    dimensionW: 'L',
    dimensionD: 'D',
    cmUnit: 'cm',
    // Artefact form
    artefactDetails: 'Manylion Arteffact',
    datePeriod: 'Cyfnod Dyddiad',
    material: 'Deunydd',
    maker: 'Arlunydd/wyr',
    makerHint: 'Kate Waters, Sarah Roberts',
    dateTimePeriod: 'Dyddiad / Cyfnod Amser',
    dateStart: 'Dechrau',
    dateEnd: 'Diwedd',
    dateDay: 'Diwrnod',
    dateMonth: 'MM',
    dateYear: 'BLWYDDYN',
    dateAD: 'OC',
    dateBC: 'CC',
    orHistoricalPeriodOrEra: 'Neu dewiswch gyfnod hanesyddol neu oes yn lle ystod dyddiad',
    periodLabel: 'Cyfnod',
    eraLabel: 'Oes',
    selectHistoricalPeriod: 'Dewiswch gyfnod hanesyddol os yn berthnasol',
    selectHistoricalEra: 'Dewiswch oes hanesyddol os yn berthnasol',
    addPeriod: '+ Ychwanegu cyfnod',
    addEra: '+ Ychwanegu oes',
    newPeriodTitle: 'Cyfnod Hanesyddol Newydd',
    newEraTitle: 'Oes Hanesyddol Newydd',
    periodNamePlaceholder: 'Enw cyfnod',
    eraNamePlaceholder: 'Enw oes',
    // Bio form
    biographyDetails: 'Manylion Bywgraffiad',
    fullName: 'Enw Llawn',
    occupation: 'Galwedigaeth',
    birthLabel: 'Geni',
    deathLabel: 'Marw',
    birthYear: 'Blwyddyn Geni',
    deathYear: 'Blwyddyn Marwolaeth',
    shortSummary: 'Crynodeb byr',
    fullBiographyContent: 'Cynnwys bywgraffiad llawn',
  },
}
